- hosts: localhost
  become: true
  become_user: root
  pre_tasks: 
    - name: Update apt
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - node
        - zsh
  tasks:
    - include: ./tasks/zsh.yml  
    - include: ./tasks/node.yml
